version: 0.2
phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
      - dpkg -i hugo_0.59.1_Linux-64bit.deb
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync --acl public-read --sse --delete ./public/ s3://$BUCKET_NAME
