version: 0.2
phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_Linux-64bit.deb
      - dpkg -i hugo_$HUGO_VERSION_Linux-64bit.deb
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync --acl public-read --sse --delete ./public/ s3://$BUCKET_NAME
