version: 0.1
phases:
    install:
        commands:
            - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
            - dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
    build:
        commands:
            - hugo
            - aws s3 sync --acl public-read --sse --delete ./public/ s3://roryhow-blog
