version: 0.1
phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
      - dpkg -i hugo_0.54.0_Linux-64bit.deb
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync --acl public-read --sse --delete ./public/ s3://roryhow-blog
